services:
  phpmyadminx:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8013:80
    environment:
      - PMA_HOST=mariadbx
  mariadbx:
    image: mariadb
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xk29dkkaDH3
    restart: unless-stopped
